### ISSUE TITLE
pod spec lint fails

### ISSUE THREAD

**Issue by jaelim-ms** [CocoaPods/fourflusher#17]
Whenever I run `pod spec lint` with CocoaPods >= 1.6.0 and <= 1.7.0 beta 2, I get below error. Have no idea of understanding the issue from error message. I could get it succeed 1-2 times out of 100 tries.
```
#<Thread:0x00007fa400d29de8@/usr/local/lib/ruby/gems/2.6.0/gems/fourflusher-2.2.0/lib/fourflusher/executable.rb:180 run> terminated with exception (report_on_exception is true):
/usr/local/lib/ruby/gems/2.6.0/gems/fourflusher-2.2.0/lib/fourflusher/executable.rb:184:in `readpartial': closed stream (IOError)
	from /usr/local/lib/ruby/gems/2.6.0/gems/fourflusher-2.2.0/lib/fourflusher/executable.rb:184:in `block (2 levels) in reader'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fourflusher-2.2.0/lib/fourflusher/executable.rb:183:in `loop'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fourflusher-2.2.0/lib/fourflusher/executable.rb:183:in `block in reader'
#<Thread:0x00007fa40138eb98@/usr/local/lib/ruby/gems/2.6.0/gems/fourflusher-2.2.0/lib/fourflusher/executable.rb:180 run> terminated with exception (report_on_exception is true):
/usr/local/lib/ruby/gems/2.6.0/gems/fourflusher-2.2.0/lib/fourflusher/executable.rb:184:in `readpartial': closed stream (IOError)
	from /usr/local/lib/ruby/gems/2.6.0/gems/fourflusher-2.2.0/lib/fourflusher/executable.rb:184:in `block (2 levels) in reader'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fourflusher-2.2.0/lib/fourflusher/executable.rb:183:in `loop'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fourflusher-2.2.0/lib/fourflusher/executable.rb:183:in `block in reader'
```

I was using Xcode 8.3.3 with CocoaPods 1.5.3 and it worked fine. After I updated Xcode to 10.1, `pod spec lint` has never succeeded.

**Comment by dnkoutso** [comment]
This is not a sufficient report for us to investigate. Currently it does not look like a cocoapods bug immediately but I can't confirm that.

Please upload sample app or repo for us to use.

Seems like a user environment/configuration issue.

**Comment by jaelim-ms** [comment]
This is a private CocoaPods repo so I can't give you an access to it. I'm getting this one, does it say something or you still need more info?
```
#<Thread:0x00007feb9ea4a3f8@/usr/local/lib/ruby/gems/2.6.0/gems/fourflusher-2.2.0/lib/fourflusher/executable.rb:180 run> terminated with exception (report_on_exception is true):
/usr/local/lib/ruby/gems/2.6.0/gems/fourflusher-2.2.0/lib/fourflusher/executable.rb:184:in `readpartial': closed stream (IOError)
	from /usr/local/lib/ruby/gems/2.6.0/gems/fourflusher-2.2.0/lib/fourflusher/executable.rb:184:in `block (2 levels) in reader'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fourflusher-2.2.0/lib/fourflusher/executable.rb:183:in `loop'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fourflusher-2.2.0/lib/fourflusher/executable.rb:183:in `block in reader'
 -> AppCenter (2.0.0-8)
    - ERROR | [iOS] unknown: Encountered an unknown error (416: unexpected token at '{
        "availability" : "(available)",
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 7 Plus",
') during validation.
```

**Comment by dnkoutso** [comment]
Seems like a bug on the available simulators in json format...what version of xcode?

**Comment by jaelim-ms** [comment]
I'm using Xcode 10.1.

**Comment by mfiebig** [comment]
Linked PR should fix this. Could you verify by adding the following to your Gemfile?

```ruby
# Temporary fix for https://github.com/CocoaPods/fourflusher/issues/17 until fourflusher (and maybe cocoapods) has a new release
gem 'fourflusher', :git => 'https://github.com/mfiebig/fourflusher.git', :ref => '4bc2ee2b12185cd976b68f2365f52e56f8ec1785'
```
