### ISSUE TITLE
Cocoapods 1.1.0.rc.3, pod validation failed caused by fourflusher

### ISSUE THREAD

**Issue by Dreddik** [CocoaPods/fourflusher#8]
Hi again.
Just updated to `Cocoapods 1.1.0.rc.3`, and now I can't validate or push a pod using  in cause of fourflusher bug.
I'm doing `
pod repo push *private_name* --use-libraries --allow-warnings --verbose --sources=*private_repo*,https://github.com/CocoaPods/Specs.git
`

But it fails with error
```
Encountered an unknown error (comparison of Fourflusher::Simulator with Fourflusher::Simulator failed
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/gems/fourflusher-2.0.0/lib/fourflusher/find.rb:132:in `sort'
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/gems/fourflusher-2.0.0/lib/fourflusher/find.rb:132:in `fetch_sims'
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/gems/fourflusher-2.0.0/lib/fourflusher/find.rb:97:in `usable_simulators'
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/gems/fourflusher-2.0.0/lib/fourflusher/find.rb:93:in `simulator'
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/gems/fourflusher-2.0.0/lib/fourflusher/xcodebuild.rb:7:in `destination'
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/gems/cocoapods-1.1.0.rc.3/lib/cocoapods/validator.rb:758:in `xcodebuild'
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/gems/cocoapods-1.1.0.rc.3/lib/cocoapods/validator.rb:518:in `block in build_pod'
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/gems/cocoapods-1.1.0.rc.3/lib/cocoapods/user_interface.rb:142:in `message'
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/gems/cocoapods-1.1.0.rc.3/lib/cocoapods/validator.rb:517:in `build_pod'
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/gems/cocoapods-1.1.0.rc.3/lib/cocoapods/validator.rb:297:in `block in perform_extensive_analysis'
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/gems/cocoapods-1.1.0.rc.3/lib/cocoapods/validator.rb:286:in `each'
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/gems/cocoapods-1.1.0.rc.3/lib/cocoapods/validator.rb:286:in `perform_extensive_analysis'
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/gems/cocoapods-1.1.0.rc.3/lib/cocoapods/validator.rb:79:in `validate'
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/gems/cocoapods-1.1.0.rc.3/lib/cocoapods/command/repo/push.rb:127:in `block in validate_podspec_files'
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/gems/cocoapods-1.1.0.rc.3/lib/cocoapods/command/repo/push.rb:121:in `each'
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/gems/cocoapods-1.1.0.rc.3/lib/cocoapods/command/repo/push.rb:121:in `validate_podspec_files'
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/gems/cocoapods-1.1.0.rc.3/lib/cocoapods/command/repo/push.rb:66:in `run'
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/gems/cocoapods-1.1.0.rc.3/lib/cocoapods/command.rb:50:in `run'
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/gems/cocoapods-1.1.0.rc.3/bin/pod:55:in `<top (required)>'
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/bin/pod:22:in `load'
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/bin/pod:22:in `<main>'
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/bin/ruby_executable_hooks:15:in `eval'
/Users/romantruba/.rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by benasher44** [comment]
Fixed in #9
